### ISSUE TITLE
Apache HTTP Client generates warning on older version usage

### ISSUE THREAD

**Issue by volphy** [aws/aws-sdk-java-v2#1372]
After upgrading AWS SDK Java v2 to 2.7.13 (latest available release), I can see the following warning message:

`
11:04:07.122 WARN [main]: s.a.a.h.a.i.utils.ApacheUtils: NoSuchMethodError was thrown when disabling normalizeUri. This indicates you are using an old version (< 4.5.8) of Apache http client. It is recommended to use http client version >= 4.5.9 to avoid the breaking change introduced in apache client 4.5.7 and the latency in exception handling. See https://github.com/aws/aws-sdk-java/issues/1919 for more information`

Apache HTTP Client has been downgraded to 4.5.7 after upgrading to the latest SDK version.

See #1168 

According to Maven Dependency plugin this version of Apache HTTP Client is a transitive dependency from:
`software.amazon.awssdk:dynamodb:jar:2.7.13:compile`

**Comment by zoewangg** [comment]
`2.7.13` should be using apache client `4.5.9`.

https://github.com/aws/aws-sdk-java-v2/blob/9443912fff5308f60df192f76e60ccccbdcfea89/pom.xml#L148

Could you run the following and provide the output?
`mvn dependency:tree -Dincludes=org.apache.httpcomponents:httpclient`?

**Comment by volphy** [comment]
I am providing anonymized, relevant excerpts from my multi-module Maven project (all modules quoted below):

`
[INFO] ***:***-core:jar:1.0-SNAPSHOT
[INFO] \- software.amazon.awssdk:dynamodb:jar:2.7.13:compile
[INFO]    \- software.amazon.awssdk:apache-client:jar:2.7.13:runtime
[INFO]       \- org.apache.httpcomponents:httpclient:jar:4.5.7:runtime

[INFO] ***:***-api:jar:1.0-SNAPSHOT
[INFO] \- ***:***-core:jar:1.0-SNAPSHOT:compile
[INFO]    \- software.amazon.awssdk:dynamodb:jar:2.7.13:compile
[INFO]       \- software.amazon.awssdk:apache-client:jar:2.7.13:runtime
[INFO]          \- org.apache.httpcomponents:httpclient:jar:4.5.7:runtime

[INFO] ***:***-main:jar:1.0-SNAPSHOT
[INFO] \- software.amazon.awssdk:dynamodb:jar:2.7.13:compile
[INFO]    \- software.amazon.awssdk:apache-client:jar:2.7.13:runtime
[INFO]       \- org.apache.httpcomponents:httpclient:jar:4.5.7:runtime
`

GroupId's and artifactId's of my modules have been replaced with asterisks.

I hope the output above is helpful.

**Comment by zoewangg** [comment]
Unfortunately, I was not able to reproduce it. 
 
```
[INFO] --- maen-dependency-plugin:2.8:tree (default-cli) @ awesome-v2 ---
[INFO] org.zoewang:awesome-v2:jar:1.0-SNAPSHOT
[INFO] \- software.amazon.awssdk:dynamodb:jar:2.7.13:compile
[INFO]    \- software.amazon.awssdk:apache-client:jar:2.7.13:runtime
[INFO]       \- org.apache.httpcomponents:httpclient:jar:4.5.9:runtime
```

Could you try purging the AWS Java SDK dependencies from your local dependencies (local .m2 folder)?  You can also try adding the apache http client `4.5.9` in your pom.xml to pin that version.

**Comment by volphy** [comment]
Purging all software.* artifacts from local Maven repository did not help.

Pinpointing Apache HTTP Client 4.5.9 (via pom.xml) helped. Though not a proper solution, it works as a viable workaround.

**Comment by volphy** [comment]
Upgrading AWS Java SDK to 2.7.19 solved the issue.

**Comment by Larykath** [comment]
Upgrading AWS Java SDK to 2.7.19 did not solve the issue for me.

**Comment by volphy** [comment]
In my case, after few more Maven operations Apache HTTP Client bumped down to 4.5.7 again.

Pinpointing helps but I am not sure if this is the right approach.

**Comment by zoewangg** [comment]
@volphy Could you provide the snippet of your `pom.xml` (the sdk dependencies should be sufficient)? Could you also elaborate on what maven commands you ran that caused the apache dependency to be bumped down?

@Larykath Could you run the following and provide the output?
`mvn dependency:tree -Dincludes=org.apache.httpcomponents:httpclient`?

**Comment by volphy** [comment]
@zoewangg 
I found the cause of my issues. My project uses Dropwizard and it brings httpclient 4.5.7:
https://github.com/dropwizard/dropwizard/blob/v1.3.14/dropwizard-bom/pom.xml


If I created simple Maven project using the following Maven archetype (pl.org.miki:java8-quickstart-archetype) and added AWS SDK DynamoDB dependency, httpclient 4.5.9 is added to the list of dependencies.

From my perspective, this issue can be closed.

**Comment by zoewangg** [comment]
@volphy Thanks for the update. In this case, I'd recommend pinpointing Apache Client to `4.5.9`.

**Comment by Larykath** [comment]
We've found the issue too. The product is referencing httpclient 4.5 on all projects.

**Comment by zoewangg** [comment]
Closing the issue. Feel free to reopen if you have further questions.

**Comment by dankolesnikov** [comment]
If you are facing this warning and running a project using `spark-submit`, a probable cause for it is Apache Spark (2.4 in my case) is using `http-client` of `4.5.6` and that class get picked up first the class loader and ignores `4.5.9` used by `aws-sdk-java-v2`.

To solve this, we simply shade this dependency in `sbt-assembly` to ensure that AWS SDK used `4.5.9` instead of `4.5.6`:
```
assemblyShadeRules in assembly := Seq(
  ShadeRule.rename("org.apache.http.**" -> "org.apache.httpShaded@1").inAll
)
```

**Comment by timmattison** [comment]
In my configuration this is what fixed it in Gradle (Kotlin DSL):

```
configurations.all {
    // Don't allow any configuration to use a broken version of HTTP client
    resolutionStrategy.force("org.apache.httpcomponents:httpclient:4.5.13")
}
```

**Comment by arianaa30** [comment]
Is WARN in the SDK is just a warning, or an Error in fact (it causes the program not to run correctly)?
